"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"
import { useRouter, usePathname } from "next/navigation"

type Language = "en" | "ar" | "fr"
type Direction = "ltr" | "rtl"

interface LanguageContextType {
  language: Language
  direction: Direction
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    home: "Home",
    events: "Events",
    about: "About",
    login: "Login",
    logout: "Logout",
    admin: "Admin Dashboard",
    search: "Search events...",
    upcoming_events: "Upcoming Events",
    past_events: "Past Events",
    event_details: "Event Details",
    date: "Date",
    time: "Time",
    location: "Location",
    description: "Description",
    register: "Register",
    create_event: "Create Event",
    edit_event: "Edit Event",
    delete_event: "Delete Event",
    export_events: "Export Events",
    import_events: "Import Events",
    title: "Title",
    start_date: "Start Date",
    end_date: "End Date",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    language: "Language",
    english: "English",
    arabic: "Arabic",
    french: "French",
    no_events: "No events found",
    loading: "Loading...",
    error: "An error occurred",
    event_created: "Event created successfully",
    event_updated: "Event updated successfully",
    event_deleted: "Event deleted successfully",
    events_imported: "Events imported successfully",
    events_exported: "Events exported successfully",
    filter: "Filter",
    all: "All",
    today: "Today",
    this_week: "This Week",
    this_month: "This Month",
    category: "Category",
    workshop: "Workshop",
    hackathon: "Hackathon",
    meetup: "Meetup",
    conference: "Conference",
    other: "Other",
    import_csv: "Import CSV",
    import_42: "Import from 42",
    export_csv: "Export as CSV",
    export_ics: "Export as ICS",
    import_42_events: "Import from 42 API",
    import_42_events_description: "Fetch and import events from the 42 Abu Dhabi API",
    fetch_42_events: "Fetch Events from 42 API",
    events_found: "events found",
    no_events_to_import: "No events to import",
    fetching: "Fetching...",
    importing: "Importing...",
    exporting: "Exporting...",
    events_fetched: "Events fetched",
    error_fetching_42_events: "Error fetching events from 42 API",
    error_importing_42_events: "Error importing events from 42 API",
    csv_format: "CSV Format",
    select_csv_file: "Select CSV File",
    please_select_file: "Please select a file",
    error_importing_events: "Error importing events",
    events_imported_count: "events imported",
    export_csv_description: "Export all events as a CSV file",
    export_ics_description: "Export all events as an ICS calendar file",
    error_exporting_events: "Error exporting events",
    events_exported_csv: "Events exported as CSV",
    events_exported_ics: "Events exported as ICS",
    import: "Import",
    export: "Export",
    import_export: "Import/Export",
    connected: "Connected",
    disconnected: "Disconnected",
    view: "View",
    edit: "Edit",
    delete: "Delete",
    delete_event_confirmation: "Are you sure you want to delete this event?",
    image_url: "Image URL",
    image_url_description: "URL to an image for the event",
    capacity: "Capacity",
    update: "Update",
    back_to_home: "Back to Home",
    login_description: "Sign in with your 42 account to access the admin dashboard",
    signing_in: "Signing in...",
    sign_in_with_42: "Sign in with 42",
    admin_access_only: "Admin access only",
    auth_error: "Authentication Error",
    auth_error_description: "There was a problem signing you in",
    error_details: "Error details",
    auth_error_help: "Try the following:",
    auth_error_help_1: "Check your internet connection",
    auth_error_help_2: "Make sure you have permission to access the admin dashboard",
    auth_error_help_3: "Try signing in again",
    try_again: "Try Again",
    new_event: "New Event",
  },
  ar: {
    home: "الرئيسية",
    events: "الفعاليات",
    about: "حول",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    admin: "لوحة الإدارة",
    search: "البحث عن الفعاليات...",
    upcoming_events: "الفعاليات القادمة",
    past_events: "الفعاليات السابقة",
    event_details: "تفاصيل الفعالية",
    date: "التاريخ",
    time: "الوقت",
    location: "الموقع",
    description: "الوصف",
    register: "التسجيل",
    create_event: "إنشاء فعالية",
    edit_event: "تعديل الفعالية",
    delete_event: "حذف الفعالية",
    export_events: "تصدير الفعاليات",
    import_events: "استيراد الفعاليات",
    title: "العنوان",
    start_date: "تاريخ البدء",
    end_date: "تاريخ الانتهاء",
    save: "حفظ",
    cancel: "إلغاء",
    confirm: "تأكيد",
    language: "اللغة",
    english: "الإنجليزية",
    arabic: "العربية",
    french: "الفرنسية",
    no_events: "لم يتم العثور على فعاليات",
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    event_created: "تم إنشاء الفعالية بنجاح",
    event_updated: "تم تحديث الفعالية بنجاح",
    event_deleted: "تم حذف الفعالية بنجاح",
    events_imported: "تم استيراد الفعاليات بنجاح",
    events_exported: "تم تصدير الفعاليات بنجاح",
    filter: "تصفية",
    all: "الكل",
    today: "اليوم",
    this_week: "هذا الأسبوع",
    this_month: "هذا الشهر",
    category: "الفئة",
    workshop: "ورشة عمل",
    hackathon: "هاكاثون",
    meetup: "لقاء",
    conference: "مؤتمر",
    other: "أخرى",
    import_csv: "استيراد CSV",
    import_42: "استيراد من 42",
    export_csv: "تصدير كملف CSV",
    export_ics: "تصدير كملف ICS",
    import_42_events: "استيراد من واجهة برمجة 42",
    import_42_events_description: "جلب واستيراد الفعاليات من واجهة برمجة 42 أبوظبي",
    fetch_42_events: "جلب الفعاليات من واجهة برمجة 42",
    events_found: "فعاليات تم العثور عليها",
    no_events_to_import: "لا توجد فعاليات للاستيراد",
    fetching: "جاري الجلب...",
    importing: "جاري الاستيراد...",
    exporting: "جاري التصدير...",
    events_fetched: "تم جلب الفعاليات",
    error_fetching_42_events: "خطأ في جلب الفعاليات من واجهة برمجة 42",
    error_importing_42_events: "خطأ في استيراد الفعاليات من واجهة برمجة 42",
    csv_format: "تنسيق CSV",
    select_csv_file: "اختر ملف CSV",
    please_select_file: "الرجاء اختيار ملف",
    error_importing_events: "خطأ في استيراد الفعاليات",
    events_imported_count: "فعاليات تم استيرادها",
    export_csv_description: "تصدير جميع الفعاليات كملف CSV",
    export_ics_description: "تصدير جميع الفعاليات كملف تقويم ICS",
    error_exporting_events: "خطأ في تصدير الفعاليات",
    events_exported_csv: "تم تصدير الفعاليات كملف CSV",
    events_exported_ics: "تم تصدير الفعاليات كملف ICS",
    import: "استيراد",
    export: "تصدير",
    import_export: "استيراد/تصدير",
    connected: "متصل",
    disconnected: "غير متصل",
    view: "عرض",
    edit: "تعديل",
    delete: "حذف",
    delete_event_confirmation: "هل أنت متأكد من رغبتك في حذف هذه الفعالية؟",
    image_url: "رابط الصورة",
    image_url_description: "رابط لصورة الفعالية",
    capacity: "السعة",
    update: "تحديث",
    back_to_home: "العودة إلى الرئيسية",
    login_description: "تسجيل الدخول بحساب 42 للوصول إلى لوحة الإدارة",
    signing_in: "جاري تسجيل الدخول...",
    sign_in_with_42: "تسجيل الدخول باستخدام 42",
    admin_access_only: "وصول المسؤول فقط",
    auth_error: "خطأ في المصادقة",
    auth_error_description: "حدثت مشكلة أثناء تسجيل دخولك",
    error_details: "تفاصيل الخطأ",
    auth_error_help: "جرب ما يلي:",
    auth_error_help_1: "تحقق من اتصالك بالإنترنت",
    auth_error_help_2: "تأكد من أن لديك إذن للوصول إلى لوحة الإدارة",
    auth_error_help_3: "حاول تسجيل الدخول مرة أخرى",
    try_again: "حاول مرة أخرى",
    new_event: "فعالية جديدة",
  },
  fr: {
    home: "Accueil",
    events: "Événements",
    about: "À propos",
    login: "Connexion",
    logout: "Déconnexion",
    admin: "Tableau de bord",
    search: "Rechercher des événements...",
    upcoming_events: "Événements à venir",
    past_events: "Événements passés",
    event_details: "Détails de l'événement",
    date: "Date",
    time: "Heure",
    location: "Lieu",
    description: "Description",
    register: "S'inscrire",
    create_event: "Créer un événement",
    edit_event: "Modifier l'événement",
    delete_event: "Supprimer l'événement",
    export_events: "Exporter les événements",
    import_events: "Importer des événements",
    title: "Titre",
    start_date: "Date de début",
    end_date: "Date de fin",
    save: "Enregistrer",
    cancel: "Annuler",
    confirm: "Confirmer",
    language: "Langue",
    english: "Anglais",
    arabic: "Arabe",
    french: "Français",
    no_events: "Aucun événement trouvé",
    loading: "Chargement...",
    error: "Une erreur est survenue",
    event_created: "Événement créé avec succès",
    event_updated: "Événement mis à jour avec succès",
    event_deleted: "Événement supprimé avec succès",
    events_imported: "Événements importés avec succès",
    events_exported: "Événements exportés avec succès",
    filter: "Filtrer",
    all: "Tous",
    today: "Aujourd'hui",
    this_week: "Cette semaine",
    this_month: "Ce mois-ci",
    category: "Catégorie",
    workshop: "Atelier",
    hackathon: "Hackathon",
    meetup: "Rencontre",
    conference: "Conférence",
    other: "Autre",
    import_csv: "Importer CSV",
    import_42: "Importer depuis 42",
    export_csv: "Exporter en CSV",
    export_ics: "Exporter en ICS",
    import_42_events: "Importer depuis l'API 42",
    import_42_events_description: "Récupérer et importer des événements depuis l'API 42 Abu Dhabi",
    fetch_42_events: "Récupérer les événements de l'API 42",
    events_found: "événements trouvés",
    no_events_to_import: "Aucun événement à importer",
    fetching: "Récupération...",
    importing: "Importation...",
    exporting: "Exportation...",
    events_fetched: "Événements récupérés",
    error_fetching_42_events: "Erreur lors de la récupération des événements depuis l'API 42",
    error_importing_42_events: "Erreur lors de l'importation des événements depuis l'API 42",
    csv_format: "Format CSV",
    select_csv_file: "Sélectionner un fichier CSV",
    please_select_file: "Veuillez sélectionner un fichier",
    error_importing_events: "Erreur lors de l'importation des événements",
    events_imported_count: "événements importés",
    export_csv_description: "Exporter tous les événements au format CSV",
    export_ics_description: "Exporter tous les événements au format calendrier ICS",
    error_exporting_events: "Erreur lors de l'exportation des événements",
    events_exported_csv: "Événements exportés au format CSV",
    events_exported_ics: "Événements exportés au format ICS",
    import: "Importer",
    export: "Exporter",
    import_export: "Importer/Exporter",
    connected: "Connecté",
    disconnected: "Déconnecté",
    view: "Voir",
    edit: "Modifier",
    delete: "Supprimer",
    delete_event_confirmation: "Êtes-vous sûr de vouloir supprimer cet événement ?",
    image_url: "URL de l'image",
    image_url_description: "URL vers une image pour l'événement",
    capacity: "Capacité",
    update: "Mettre à jour",
    back_to_home: "Retour à l'accueil",
    login_description: "Connectez-vous avec votre compte 42 pour accéder au tableau de bord",
    signing_in: "Connexion en cours...",
    sign_in_with_42: "Se connecter avec 42",
    admin_access_only: "Accès administrateur uniquement",
    auth_error: "Erreur d'authentification",
    auth_error_description: "Un problème est survenu lors de votre connexion",
    error_details: "Détails de l'erreur",
    auth_error_help: "Essayez ce qui suit :",
    auth_error_help_1: "Vérifiez votre connexion Internet",
    auth_error_help_2: "Assurez-vous d'avoir l'autorisation d'accéder au tableau de bord",
    auth_error_help_3: "Essayez de vous reconnecter",
    try_again: "Réessayer",
    new_event: "Nouvel événement",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({
  children,
  defaultLanguage = "en",
}: {
  children: React.ReactNode
  defaultLanguage?: Language
}) {
  const [language, setLanguage] = useState<Language>(defaultLanguage)
  const router = useRouter()
  const pathname = usePathname()

  useEffect(() => {
    const lang = pathname.split("/")[1] as Language
    if (lang && ["en", "ar", "fr"].includes(lang)) {
      setLanguage(lang)
    }
  }, [pathname])

  const handleLanguageChange = (newLang: Language) => {
    setLanguage(newLang)
    const newPath = pathname.replace(/^\/[a-z]{2}/, `/${newLang}`)
    router.push(newPath)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
